### PR TITLE
flake.nix: update to latest as of September 5th, 2024

### PR DESCRIPTION
**Pull request by philiptaron**
Pretty simple. I did a test build on `x86_64-linux`.

### CODE REVIEW

**Comment by bobbobbio** [comment]
Last time I tried to update this, I had an issue with the protobuf package, can you confirm its working? you just need to run `py/protobuf_compile.sh`

**Comment by bobbobbio** [comment]
I opened this issue for it https://github.com/NixOS/nixpkgs/issues/333054

**Comment by philiptaron** [comment]
See what you think of this, Remi (@bobbobbio).

**Comment by bobbobbio** [comment]
works for me

**Comment by philiptaron** [comment]
I assigned the nixpkgs issue to myself, though I know only a little bit about Nix + Python. Chance to learn, etc. etc.

Hope you're well. Love to see the progress on Maelstrom!

**Comment by philiptaron** [comment]
Wait, what's the CI failure? https://github.com/maelstrom-software/maelstrom/actions/runs/10727494332/job/29749948178

**Comment by bobbobbio** [comment]
I've seen this issue before but I wasn't able to fix it. It seems to be a problem with certain nix versions of Rust and it only shows up on the github workers. I was only able to fix it before by using some older version of the package.

**Comment by bobbobbio** [comment]
okay, reverting the `nixpkgs` part of the update has fixed the build. I'm not sure whats wrong, and its hard to debug since it doesn't happen locally.

> I assigned the nixpkgs issue to myself, though I know only a little bit about Nix + Python. Chance to learn, etc. etc.
> Hope you're well. Love to see the progress on Maelstrom!
Thanks Philip, I hope you are doing well too. Thank you for your work on this PR and any work on that nix issue.

**Comment by philiptaron** [comment]
> its hard to debug since it doesn't happen locally.

I _do_ see it locally on NixOS btw.

**Comment by bobbobbio** [comment]
I made this issue to track the blocked update of nixpkgs https://github.com/maelstrom-software/maelstrom/issues/412

**Pull request merged**
